# Path to log folder
log_path: "advanced_logs"

# Enable or disable log types
log_types:
  PLAYER_LOGIN: true
  PLAYER_QUIT: true
  PLAYER_ADVANCEMENT: true
  PLAYER_COMMAND: true
  PLAYER_DEATH: true
  PLAYER_KILL_PLAYER: true
  PLAYER_PICKUP_ITEM_DROP: true
  PLAYER_PICKUP_ITEM_CHEST: true
  SERVER_START: true
  SERVER_STOP: true
  PLAYER_CHAT: true