package com.github.bbugsco.advancedlog.Logging;

public enum LogType {
    PLAYER_LOGIN,
    PLAYER_QUIT,
    PLAYER_ADVANCEMENT,
    PLAYER_LOCATION,
    PLAYER_COMMAND,
    PLAYER_DEATH,
    PLAYER_KILL_PLAYER,
    PLAYER_PICKUP_ITEM_DROP,
    PLAYER_PICKUP_ITEM_CHEST,
    SERVER_START,
    SERVER_STOP
}